// Generated by CoffeeScript 1.9.3
(function() {
  var Lobby, lobby;

  Lobby = require("./Lobby");

  console.log("[Game] Ogar - An open source Agar.io server implementation");

  lobby = new Lobby();

  lobby.start();

}).call(this);

//# sourceMappingURL=Server.js.map
